[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
proof_of_dicipline = "CBahuq4hPsMgdgqqM7f63BC1spvAvANWHhuhmCcz9F3u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
